### ISSUE TITLE
execute callback mid-loading

### ISSUE THREAD

**Issue by artknight** [w3core/import.js#1]
Hi,
is it possible to load a few scripts, then execute a callback to ... say `init` some methods ... and then load the rest of the scripts?

Thanks,

**Comment by w3core** [comment]
Sure.

You can handle `@import:some-name` event in the document where `some-name` is an optional `name` parameter of some script after then you can load additional (required scripts).

For example the named script is `angular` and additional scripts are some angular plugins.
