### ISSUE TITLE
Load css type twice

### ISSUE THREAD

**Issue by limodou** [w3core/import.js#2]
This lib is very small, I like it. But when I used it, I found it'll fetch css type twice, and I found the code is:

```
    NODES.push(node);
    head.appendChild(node);
    if(!js) img.src = inf.url;
    return node;
```

I think the `if(!js) img.src = inf.url` is not right, when I removed it, the behave is right. So is it a bug?

**Comment by limodou** [comment]
It seems if I comment the line`img.src` the process will be not right. And I don't know if the css file will be fetch twice?

**Comment by w3core** [comment]
Some browsers, mainly some mobile browsers, does not dispatch the "load" event for the "link" stylesheet tag. More information about that you can find here http://www.backalleycoder.com/2011/03/20/link-tag-css-stylesheet-load-event/ . So, to be sure that stylesheet has been loaded, we should use workaround that loads stylesheet twice.

**Comment by szkrd** [comment]
Hi Max, is this still the case? I could not find anything after 2012 that still suggests inconsistent behaviour for stylesheet onload. Probably you have seen this problem in the live, where did you experience it? I've seen your comment on David Wals's blog, which is 2016, so I ended up here :)
